---
- name: Patch and install http package
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Apache HTTP server
      apt:
        name: apache2
        state: present

    - name: Ensure Apache is enabled and running
      service:
        name: apache2
        state: started
        enabled: yes
